server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway
#https://dev-77584981.okta.com/oauth2/default
#okta:
#  oauth2:
#    issuer:  https://dev-29404049.okta.com
#    audience: api//authorize
#    client-id: KnKI7pyDJnmBH8l5Kc9KpCja6h1iima0
#    client-secret: rIqJNAnweoV4iHAX2HHQcea4_ePbyMYh8IWs6WfVZvcGZE__Aea_y7uEDiKGQ8xB
#    scopes: openid+profile+email+offline_acces
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.auth0.example: TRACE

okta:
  oauth2:
    issuer: https://dev-4lk6zlk472clxklc.us.auth0.com/
    client-id: uhyKTrikZSBauojnv4fFe0FLpSjwXN0p
    client-secret: PCNL2tFpb2v6c7jazbZnJ3RC0qeQtYcVezDhfdvBFFCncGPwviEwotYQYYLgIC7j

#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: KnKI7pyDJnmBH8l5Kc9KpCja6h1iima0
#            client-secret: rIqJNAnweoV4iHAX2HHQcea4_ePbyMYh8IWs6WfVZvcGZE__Aea_y7uEDiKGQ8xB
#        provider:
#          okta:
#           issuer-uri: https://dev-29404049.okta.com





